name: OIDC Lab - Assume Role and Read Flag
on:                                                                                          
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  read-flag:
    runs-on: ubuntu-latest                                                                   
    steps:
      - name: Configure AWS Credentials via OIDC                                             
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981796476:role/sts-lab-2-target
          role-session-name: oidc-lab-session                                                
          aws-region: us-east-1
          audience: sts.amazonaws.com                                                        
                                                                                               
      - name: Verify Identity
        run: aws sts get-caller-identity                                                     
                  
      - name: List Secrets
        run: aws secretsmanager list-secrets --region us-east-1 --query 'SecretList[*].Name' --output text
                                                                                               
      - name: Read Flag                                                                      
        run: aws secretsmanager get-secret-value --secret-id flag_sts_lab_2 --region us-east-1       
